/*
 * This source file was generated by the Gradle 'init' task
 */
package pagos;

import java.util.Scanner;

import pagos.model.Bitcoin;
import pagos.model.Paypal;
import pagos.model.TarjetaCredito;
import pagos.model.Producto;
import pagos.model.CarroCompra;

public class App {

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        CarroCompra carro = new CarroCompra();
        carro.agregarProducto(new Producto("Notebook", 670000));
        carro.agregarProducto(new Producto("Mouse", 25000));

        boolean salir = true;
        int opcion = 0;
        while (salir) {
            System.out.println("Seleccione el método de pago:");
            System.out.println("1. Paypal");
            System.out.println("2. Bitcoin");
            System.out.println("3. Tarjeta de Crédito");
            System.out.println("4. Mostrar productos en el carro de compra");
            System.out.println("5. Remover producto por nombre");
            System.out.println("6. Salir");
            opcion = scanner.nextInt();
            switch (opcion) {
                case 1:
                    carro.checkout(new Paypal("cristiantorr79@gmail.com"));
                    break;
                case 2:
                    carro.checkout(new Bitcoin("1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa"));
                    break;
                case 3:
                    carro.checkout(new TarjetaCredito("1234-5678-9012-3456"));
                    break;
                case 4:
                    carro.mostrarProductos();
                    break;
                case 5:
                    System.out.println("Ingrese el nombre del producto a remover:");
                    scanner.nextLine(); // Consumir el salto de línea pendiente
                    String nombre = scanner.next();
                    carro.removerProductoPorNombre(nombre);
                    break;
                case 6:
                    salir = false;
                    System.out.println("Saliendo del programa.");
                    break;
                default:
                    System.out.println("Opción no válida. Intente de nuevo.");
                    break;
            }
        }
        scanner.close();
    }
}